### ISSUE TITLE
Matplotlib not working

### ISSUE THREAD

**Issue by DeannaLinn** [learn-co-curriculum/dsc-1-01-08-your-first-data-science-codealong#2]
ModuleNotFoundErrorTraceback (most recent call last)
<ipython-input-2-271c0420254e> in <module>()
      1 import pandas as pd
----> 2 import matplotlib.pyplot as plt
      3 get_ipython().run_line_magic('matplotlib', 'inline')

ModuleNotFoundError: No module named 'matplotlib'

**Comment by PeterBell** [comment]
We updated the docker instance, so this should work for you now if you're doing it online. Closing issue, but open again if you're still having problems!
